#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


URL="https://github.com/Rigolo/tv-grab-file/archive/master.zip"

dl $URL /opt/
