#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}


URL="https://raw.githubusercontent.com/Rigolo/tv-grab-file/master/tv_grab_file"

dl $URL /usr/local/src
