#!/bin/sh -ex

SRC=/usr/local/src
BIN=/usr/local/bin

apt-get update

DEBIAN_FRONTEND=noninteractive apt-get -y install tvheadend

#Enable Adding TV Guide From File
mv $SRC/tv_grab_file $BIN/tv_grab_file
chmod +x $BIN/tv_grab_file

# enabled nginx reverse proxy
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/tvheadend /etc/nginx/sites-enabled/tvheadend
