#!/bin/sh -ex

SRC=/usr/local/src
SRC2=/opt/

apt-get update

DEBIAN_FRONTEND=noninteractive apt-get -y install tvheadend

#Enable Adding TV Guide From File
unzip $SRC2/master.zip -d /usr/bin
rm $SRC2/master.zip
mv /usr/bin/tv-grab-file-master/tv_grab_file /usr/bin/tv_grab_file
rm -rf /usr/bin/tv-grab-file-master

# enabled nginx reverse proxy
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/tvheadend /etc/nginx/sites-enabled/tvheadend
