#!/bin/sh -ex

SRC=/usr/local/src
SRC2=/opt/

wget -qO- https://doozer.io/keys/tvheadend/tvheadend/pgp | apt-key add -

echo "deb http://apt.tvheadend.org/unstable stretch main" | tee -a /etc/apt/sources.list.d/tvheadend.list

apt-get update

DEBIAN_FRONTEND=noninteractive apt-get -y install tvheadend

unzip $SRC2/master.zip -d /usr/bin
rm $SRC2/master.zip
mv /usr/bin/tv-grab-file-master/tv_grab_file /usr/bin/tv_grab_file
rm -rf /usr/bin/tv-grab-file-master